plugins:
  # Core
  projects_enabled:
    default: true
    client: false
  projects_private:
    default: true
    client: false

  # Banner
  projects_banner:
    default: true
    client: true
  projects_banner_sticky:
    default: true
    client: true
  projects_banner_min_level:
    default: 0
    min: 0
    max: 4
    client: true
  projects_banner_max_level:
    default: 4
    min: 0
    max: 4
    client: true
  projects_banner_routes:
    default: "discovery|subcategories|projectMembers|topic!"
    type: list
    client: true

  # Breadcrumb
  projects_breadcrumb_project_dropdown:
    default: true
    client: true
  projects_breadcrumb_subcategory_links:
    default: false
    client: true

  # Navigation
  projects_link_to_subcategories:
    default: false
    client: true
  projects_sync_category_discovery_nav:
    default: false
    client: true
  projects_hide_navigation_menu_categories:
    default: false
    client: true
  projects_highlight_projects_sidebar_link:
    default: true
    client: true
  projects_home_logo_to_projects:
    default: false
    client: true

  # Categories
  projects_category_requires_parent:
    default: true
    client: true
  projects_sort_categories_alphabetically:
    default: true
    client: false
  projects_hide_projects_from_categories_page:
    default: false
    client: true

  # Styling
  projects_addon:
    default: true
    client: true
  projects_styled_links:
    default: true
    client: true
  projects_show_logo_placeholder:
    default: true
    client: true
